on:
    push:
    pull_request:

name: CI
jobs:
  build_and_test:
    name: OS Test
    strategy:
      fail-fast: false
      matrix:
        rust-version:
          - nightly
          - stable
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}
      - name: Build
        run: cargo build --all --verbose
      - name: Test
        run: cargo test --all --verbose
  lint:
    name: Clippy and fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Check formatting
        run: cargo fmt --check
      - name: Check for clippy lints
        run: cargo clippy
